version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install requiremenst libraries
          command: |
            python3 -m venv .env
            . .env/bin/activate
            sudo apt install -y swig mecab libmecab-dev mecab-ipadic-utf8
            curl -L -o CRF++-0.58.tar.gz 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7QVR6VXJ5dWExSTQ'
            sudo tar zxf CRF++-0.58.tar.gz
            sudo ./configure
            sudo make
            sudo make install
            sudo ldconfig
            cd ../
            curl -c  cabocha-0.69.tar.bz2 -s -L 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7SDd1Q1dUQkZQaUU' |grep confirm |  sed -e "s/^.*confirm=\(.*\)&amp;id=.*$/\1/" | xargs -I{}
            curl -b  cabocha-0.69.tar.bz2 -L -o cabocha-0.69.tar.bz2 'https://drive.google.com/uc?confirm={}&export=download&id=0B4y35FiV1wh7SDd1Q1dUQkZQaUU'
            tar xjf cabocha-0.69.tar.bz2
            sudo curl -c  cabocha-0.69.tar.bz2 -s -L 'https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7SDd1Q1dUQkZQaUU' |grep confirm |  sed -e "s/^.*confirm=\(.*\)&amp;id=.*$/\1/" | xargs -I{}
            sudo curl -b  cabocha-0.69.tar.bz2 -L -o cabocha-0.69.tar.bz2 'https://drive.google.com/uc?confirm={}&export=download&id=0B4y35FiV1wh7SDd1Q1dUQkZQaUU'
            sudo tar xjf cabocha-0.69.tar.bz2
            cd cabocha-0.69
            sudo ./configure --with-mecab-config='which mecab-config' --with-charset=UTF8
            sudo make
            sudo make install
            sudo ldconfig
            cd python
            sudo python3 setup.py install
            cd ../../
            rm -rf CRF++-0.58* cabocha-0.69*
            git clone https://github.com/brendano/stanford_corenlp_pywrapper
            cd stanford_corenlp_pywrapper
            pip install .
            cd ../
            rm -rf stanford_corenlp_pywrapper
      - restore_cache:
          keys:
          - requirements-{{ checksum "requirements.txt" }}
      - run:
          name: Run tox
          command: |
            . .env/bin/activate
            pip install -U pip tox flake8
            pip install -r requirements.txt
            tox
      - save_cache:
          paths:
            - .env
            - .tox
          key: requirements-{{ checksum "requirements.txt" }}

workflows:
  version: 2
  codetest:
    jobs:
      - test
